---
title: "Welcome To My Blog"
author: "cbarz"
date: "2022-11-24"
categories: [news]
---

# Welcome

Add some welcome text.

- blog will be mainly about mathematical optimization
- objects basic notions from stochastic programming (as short high level intro for colleagues with no optimization background)


## setup

Let summarize the steps to reproduce such a blog.
This is mainly written for myself to avoid reading multiple 


1. Create a github repo and clone it with SSH
1. Create conda env and add packages (we use solvers from conda forge)
```
conda create --name SP_blog python=3.8
conda install -c conda-forge poetry
poetry init
poetry add pandas jupyterlab pyomo
conda install -c conda-forge ipopt glpk coincbc
```
1. create quarto blog project
```
quarto create-project SP_blog --type website:blog
```
1. move content from created folder `SP_blog` to the root directory

## render blog with Github pagese from `docs`

1. modify `quarto.yml`
```
project:
  type: website
  output-dir: docs
```
1. add a `.nojekyll` to root of repository
```
touch .nojekyll
```
1. configure Github repo [add picture](https://quarto.org/docs/publishing/github-pages.html)
- go settings 
- go pages 
- select publish from branch (suggested main) and `docs` directory
deployment can take a while


## creating post 
1. for a new blog create a folder in the `posts` folder
1. create an `index.qmd` or `index.ipynb` file with blog content
1. inspect result with `quarto preview`
1. render, commit and push
```
quarto render
git status
git add .
git commit -m "commit message"
git push
```





## sources

- https://quarto.org/docs/publishing/github-pages.html
- https://quarto.org/docs/websites/website-blog.html
- https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent