# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/quarto_blog_test',
                'doc_host': 'https://barz-christian.github.io',
                'git_url': 'https://github.com/barz-christian/quarto_blog_test',
                'lib_path': 'SP_blog'},
  'syms': {'SP_blog.core': {'SP_blog.core.foo': ('core.html#foo', 'SP_blog/core.py')}}}
