name: CI
on:  [workflow_dispatch, pull_request, push]

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: install solver
        run : sudo apt-get install -y libopenmpi-dev glpk-utils
      - name: poetry install
        run: |
          python -m pip install --upgrade pip
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install
      - uses: fastai/workflows/quarto-ghp@master
      - uses: fastai/workflows/nbdev-ci@master
